### ISSUE TITLE
can't serialize class java.math.BigDecimal

### ISSUE THREAD

**Issue by pkvov** [congomongo/congomongo#148] opened 2017-05-11 09:26 UTC
the java driver fixed the issue few days ago
[JAVA-2423](https://jira.mongodb.org/browse/JAVA-2423)

**Comment by seancorfield** [comment] 2017-10-06 06:29
I’ll link to this thread as explanation for why nothing has happened with this issue:

https://groups.google.com/forum/m/#!topic/congomongo-dev/Wpq1TbtFRHU

**Comment by jheander** [comment] 2018-05-02 10:03
This requires upgrading to the 3.0 version of the MongoDB java driver, therefore duplicate of #134

**Closed by jheander** 2018-05-02 10:03 UTC
